
name: 💡 Feature request
description: Suggest new functionality, new content or balancing changes
labels: [feature request]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to improve
    validations:
      required: true